PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE infos(id integer PRIMARY KEY,name text,text text,zone integer default 3, dateAdded datetime, lastModified datetime, votes integer default 0 not null, rating integer default 0 not null, expiration datetime, exp_action integer, date dateTime);
CREATE TABLE category_alias (id integer PRIMARY KEY, category_id integer, name string, Unique (name));
CREATE TABLE disks_bez (id integer PRIMARY KEY, name string, bez string, Unique (name));
CREATE TABLE item_ref(id integer PRIMARY KEY,item1_id integer, item1_type_id integer, item2_id integer, item2_type_id integer, unique (item1_id, item1_type_id, item2_id, item2_type_id));
CREATE TABLE links(id integer PRIMARY KEY,name text,mediatype text,source text,mirror text,dateAdded datetime,zone integer default 3, pid integer, fid integer, votes integer default 0 not null, rating integer default 0 not null, unique (source));
CREATE TABLE zone_bez (id integer PRIMARY KEY, zone integer, bez string, Unique (zone));
CREATE TABLE zones (id integer PRIMARY KEY, zones integer, zone integer, Unique (zones,zone));
CREATE TABLE category_item(id integer PRIMARY KEY,category_id integer not null,item_id integer not null,item_type_id integer not null,UNIQUE (category_id,item_id,item_type_id));
CREATE TABLE history(item_id integer, item_type_id integer, search_term text, categories text, ex_categories text, zones integer, timestamp datetime, command text, parameters text, output text);
CREATE TABLE category(id integer PRIMARY KEY,name text,parent integer, zone integer,UNIQUE (name));
CREATE TABLE files(id integer PRIMARY KEY,name text,mediatype text,disksource text,inode integer,bdisksource text,binode integer,source text,zone integer default 3, votes integer default 0 not null, rating integer default 0 not null, UNIQUE (disksource,inode));
CREATE VIEW category_link as select category_id, item_id from category_item where item_type_id=2;
CREATE VIEW category_info as select category_id, item_id from category_item where item_type_id=1;
CREATE VIEW v_infos as select * from infos;
CREATE VIEW category_file as select category_id, item_id from category_item where item_type_id=3;
CREATE VIEW v_links as select *,dateAdded as date from links;
CREATE VIEW v_files as select *,Null as dateAdded,Null as date from files;

insert into infos default values;
-- add system category
INSERT INTO "category" VALUES(1,'use_clipboard',0,0);
INSERT INTO "category" VALUES(2,'check',0,3);
INSERT INTO "category" VALUES(3,'weekly',7,3);
INSERT INTO "category" VALUES(4,'monthly',7,3);
INSERT INTO "category" VALUES(5,'todo',0,3);
INSERT INTO "category" VALUES(6,'biweekly',7,3);
INSERT INTO "category" VALUES(7,'periodical',0,3);
INSERT INTO "category" VALUES(8,'blacklist',0,3);
INSERT INTO "category" VALUES(9,'yearly',0,3);
INSERT INTO "category" VALUES(10,'done',0,7);

-- add default zones
INSERT INTO "zones" VALUES(1,1,1);
INSERT INTO "zones" VALUES(2,1,3);
INSERT INTO "zones" VALUES(5,2,2);
INSERT INTO "zones" VALUES(6,2,3);
INSERT INTO "zones" VALUES(9,4,4);
INSERT INTO "zones" VALUES(13,3,1);
INSERT INTO "zones" VALUES(14,3,2);
INSERT INTO "zones" VALUES(15,3,3);
INSERT INTO "zones" VALUES(16,3,7);
INSERT INTO "zones" VALUES(17,5,1);
INSERT INTO "zones" VALUES(19,5,5);
INSERT INTO "zones" VALUES(20,5,7);
INSERT INTO "zones" VALUES(21,6,2);
INSERT INTO "zones" VALUES(23,6,6);
INSERT INTO "zones" VALUES(24,6,7);
INSERT INTO "zones" VALUES(25,7,1);
INSERT INTO "zones" VALUES(26,7,2);
INSERT INTO "zones" VALUES(28,7,3);
INSERT INTO "zones" VALUES(29,7,5);
INSERT INTO "zones" VALUES(30,7,6);
INSERT INTO "zones" VALUES(31,7,7);
INSERT INTO "zones" VALUES(32,4,1);
INSERT INTO "zones" VALUES(33,4,3);
INSERT INTO "zones" VALUES(34,4,7);
INSERT INTO "zones" VALUES(35,8,1);
INSERT INTO "zones" VALUES(36,8,2);
INSERT INTO "zones" VALUES(37,8,3);
INSERT INTO "zones" VALUES(38,8,8);
INSERT INTO "zones" VALUES(39,8,9);
INSERT INTO "zones" VALUES(40,8,10);
INSERT INTO "zones" VALUES(41,8,11);
INSERT INTO "zones" VALUES(42,9,1);
INSERT INTO "zones" VALUES(43,9,3);
INSERT INTO "zones" VALUES(44,9,8);
INSERT INTO "zones" VALUES(45,9,9);
INSERT INTO "zones" VALUES(46,9,11);
INSERT INTO "zones" VALUES(47,10,2);
INSERT INTO "zones" VALUES(48,10,3);
INSERT INTO "zones" VALUES(49,10,8);
INSERT INTO "zones" VALUES(50,10,10);
INSERT INTO "zones" VALUES(51,10,11);
INSERT INTO "zones" VALUES(52,12,1);
INSERT INTO "zones" VALUES(53,12,3);
INSERT INTO "zones" VALUES(54,12,4);
INSERT INTO "zones" VALUES(55,12,5);
INSERT INTO "zones" VALUES(56,12,7);
INSERT INTO "zones" VALUES(57,12,8);
INSERT INTO "zones" VALUES(58,12,9);
INSERT INTO "zones" VALUES(59,12,11);
INSERT INTO "zones" VALUES(60,12,12);
INSERT INTO "zones" VALUES(61,13,1);
INSERT INTO "zones" VALUES(62,13,3);
INSERT INTO "zones" VALUES(64,13,5);
INSERT INTO "zones" VALUES(65,13,7);
INSERT INTO "zones" VALUES(66,13,8);
INSERT INTO "zones" VALUES(67,13,9);
INSERT INTO "zones" VALUES(68,13,11);
INSERT INTO "zones" VALUES(70,13,13);
INSERT INTO "zones" VALUES(71,13,15);
INSERT INTO "zones" VALUES(72,14,2);
INSERT INTO "zones" VALUES(73,14,3);
INSERT INTO "zones" VALUES(74,14,6);
INSERT INTO "zones" VALUES(75,14,7);
INSERT INTO "zones" VALUES(76,14,8);
INSERT INTO "zones" VALUES(77,14,10);
INSERT INTO "zones" VALUES(78,14,11);
INSERT INTO "zones" VALUES(79,14,12);
INSERT INTO "zones" VALUES(80,14,14);
INSERT INTO "zones" VALUES(81,14,15);
INSERT INTO "zones" VALUES(82,15,1);
INSERT INTO "zones" VALUES(83,15,2);
INSERT INTO "zones" VALUES(84,15,3);
INSERT INTO "zones" VALUES(85,15,5);
INSERT INTO "zones" VALUES(86,15,6);
INSERT INTO "zones" VALUES(87,15,7);
INSERT INTO "zones" VALUES(88,15,8);
INSERT INTO "zones" VALUES(89,15,9);
INSERT INTO "zones" VALUES(90,15,10);
INSERT INTO "zones" VALUES(91,15,11);
INSERT INTO "zones" VALUES(92,15,13);
INSERT INTO "zones" VALUES(93,15,14);
INSERT INTO "zones" VALUES(94,15,15);
INSERT INTO "zones" VALUES(95,5,3);
INSERT INTO "zones" VALUES(96,4,5);
INSERT INTO "zones" VALUES(97,1,9);
INSERT INTO "zones" VALUES(98,2,10);
INSERT INTO "zones" VALUES(99,3,9);
INSERT INTO "zones" VALUES(100,3,10);
INSERT INTO "zones" VALUES(101,3,11);
INSERT INTO "zones" VALUES(102,5,9);
INSERT INTO "zones" VALUES(103,5,11);

CREATE TABLE cronjobs(id integer PRIMARY KEY,name text, lastModified datetime);
INSERT INTO "cronjobs" VALUES(1,'daily',(select date()));
INSERT INTO "cronjobs" VALUES(2,'weekly',(select date()));

COMMIT;
